package tests.day09;

import org.junit.Test;
import org.openqa.selenium.Cookie;
import utilities.TestBase;

import java.util.Set;

public class Day09_Cookies_ extends TestBase {
    /*
        Cookies are temporary data that is generated by browser.
        It's the way for a website to remember you, your preferences and your habits on web.
    */
    /*
        Given
                Go to "https://www.amazon.com"
        When
                Find the total number of cookies
        And
                Print all the cookies
        And
                Get the cookies by their name
        And
                Add new cookie
        And
                Delete cookie by name
        And
                Delete all the cookies
    */

    @Test
    public void cookiesTest() throws InterruptedException {

        // Go to "https://www.amazon.com"
        driver.get("https://www.amazon.com");
        
        // Find the total number of cookies
        Set<Cookie> allCookies = driver.manage().getCookies();
        System.out.println("Number Of Cookies = " + allCookies.size());

        // Print all the cookies
        for (Cookie eachCookie : allCookies){
            System.out.println("Cookie: " + eachCookie);
            System.out.println("Cookie Value: " + eachCookie.getValue());
            System.out.println("Cookie Name: " + eachCookie.getName());
        }
        
        // Get the cookies by their name
        Cookie cookieNamed = driver.manage().getCookieNamed("sp-cdn");
        System.out.println("cookieNamed = " + cookieNamed);
        
        // Add new cookie
        Cookie newCookie = new Cookie("My-Cookie","apple-pie");
        driver.manage().addCookie(newCookie);
        Thread.sleep(2000);
        int numOfCookies = driver.manage().getCookies().size();
        System.out.println("numOfCookies = " + numOfCookies);

        // Delete cookie by name
        driver.manage().deleteCookieNamed("csm-hit");
        System.out.println("Number of Cookies after delete: " + driver.manage().getCookies().size());

        // Delete all Cookies
        driver.manage().deleteAllCookies();
        System.out.println("Number of Cookies after delete all: " + driver.manage().getCookies().size());
    }
}
